### ISSUE TITLE
Breaks if you don't pass in width or height

### ISSUE THREAD

**Issue by axelson** [BWheatie/scenic_layout_o_matic#19]
Example error:
```
Launcher.Scene.Home crashed during init
Scene Args: nil
%CaseClauseError{term: %{button_font_size: 25}}
-->     (scenic_layout_o_matic) lib/layouts/components/button.ex:25: LayoutOMatic.Layouts.Components.Button.translate/1
    (scenic_layout_o_matic) lib/layouts/components/autolayout.ex:88: LayoutOMatic.Layouts.Components.AutoLayout.do_layout/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (scenic_layout_o_matic) lib/layouts/components/autolayout.ex:62: LayoutOMatic.Layouts.Components.AutoLayout.auto_layout/3
    (launcher) lib/launcher/scenes/home.ex:98: Launcher.Scene.Home.add_buttons_to_graph/1
    (launcher) lib/launcher/scenes/home.ex:66: Launcher.Scene.Home.init/2
    (scenic) lib/scenic/scene.ex:866: Scenic.Scene.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
```

**Comment by BWheatie** [comment]
Fixed with #27
